<?php

/**
 * @file
 * Require users to spend time on selected pages in order to access additional
 * pages.
 */

/**
 * Implements hook_menu().
 */
function timeaccess_menu() {
  $items['admin/build/timeaccess/list'] = array(
    'title' => 'TimeAccess',
    'page callback' => 'timeaccess_list_rulesets',
    'access arguments' => array('administer timeaccess'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'file' => 'timeaccess.admin.inc',
  );
  $items['admin/build/timeaccess/add'] = array(
    'title' => 'Add ruleset',
    'page callback' => 'timeaccess_add_rulesets',
    'access arguments' => array('administer timeaccess'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'file' => 'timeaccess.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_perm().
 */
function timeaccess_perm() {
  return array('administer timeaccess', 'override access permissions');
}
